# Install dependencies only when needed
FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

# Rebuild the source code only when needed
FROM node:20-alpine AS builder
WORKDIR /app
COPY . .
COPY --from=deps /app/node_modules ./node_modules

# Development image, copy all the files and run dev
FROM node:16-alpine AS dev
WORKDIR /app

ENV NODE_ENV development

# Copy the files from the builder stage
COPY --from=builder /app ./

# Copy the .env file to the container
COPY .env .env

# Expose the development server port
EXPOSE 3000

# Start the Next.js development server
CMD ["npm", "run", "dev"]
