export const businessProcessJson = {
    pages: [
        {
            name: "business-process-creator",
            title: "Business Process Creator",
            elements: [
                {
                    type: "text",
                    name: "name",
                    title: "Business Process Name",
                    titleLocation: "top",
                    isRequired: true,
                    maxLength: 100,
                    placeholder: "Enter business process name",
                },
                {
                    type: "comment",
                    name: "description",
                    title: "Description",
                    isRequired: true,
                    autoGrow: true,
                    placeholder: "Enter description",
                },
                {
                    type: "boolean",
                    name: "allowAlwaysEdit",
                    title: "Always Editable",
                    labelTrue: "Yes",
                    labelFalse: "No",
                    defaultValue: false,
                },
                {
                    type: "boolean",
                    name: "allowBpStartersViewAll",
                    title: "BP Starters Can View All",
                    labelTrue: "Yes",
                    labelFalse: "No",
                    defaultValue: false,
                },
                {
                    type: "boolean",
                    name: "allowElevatedViewAll",
                    title: "Elevated Users Can View All",
                    labelTrue: "Yes",
                    labelFalse: "No",
                    defaultValue: false,
                },
                {
                    type: "boolean",
                    name: "startByDefault",
                    title: "Start By Default",
                    labelTrue: "Yes",
                    labelFalse: "No",
                    defaultValue: true,
                },
                {
                    type: "boolean",
                    name: "isActive",
                    title: "Is Active?",
                    labelTrue: "Yes",
                    labelFalse: "No",
                    defaultValue: true,
                },
                {
                    type: "text",
                    name: "startDate",
                    title: "Start Date",
                    inputType: "date",
                    placeholder: "Enter start date",
                },
                {
                    type: "number",
                    name: "noOfDaysLiveAfterBpStart",
                    title: "Days Live After BP Start",
                    min: 1,
                    max: 365,
                    defaultValue: null,
                },
                {
                    type: "number",
                    name: "noOfDaysLiveAfterWfStart",
                    title: "Days Live After WF Start",
                    min: 1,
                    max: 365,
                    defaultValue: null,
                },
            ],
        },
    ],
};
