export const businessProcessJson = {
  pages: [
    {
      name: "basic-details",
      title: "Basic Details",
      elements: [
        {
          type: "text",
          name: "name",
          title: "Business Process Name",
          titleLocation: "top",
          isRequired: true,
          placeholder: "Enter business process name",
        },
        {
          type: "boolean",
          name: "isActive",
          title: "Is Active?",
          labelTrue: "Yes",
          labelFalse: "No",
          defaultValue: true,
          startWithNewLine: false,
        },
        {
          type: "boolean",
          name: "isExternalBusinessProcess",
          title: "Is this for EU roles to complete?",
          labelTrue: "Yes",
          labelFalse: "No",
          defaultValue: false,
          startWithNewLine: false,
        },
        {
          type: "comment",
          name: "description",
          title: "Description",
          isRequired: true,
          autoGrow: true,
          placeholder: "Enter description",
        },
        {
          type: "dropdown",
          name: "formId",
          isRequired: true,
          title: "Survey JS Form",
          choicesByUrl: {
            url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/form/allBy`,
            path: "resource",
            valueName: "id",
            titleName: "name",
          },
        },
        {
          type: "tagbox",
          name: "userAccessGroupNames",
          title: "User Access Group Names",
          titleLocation: "top",
          placeholder: "Enter user access group names",
          choicesByUrl: {
            url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/userGroupPlatform`,
            path: "resource",
            valueName: "name",
            titleName: "name",
          },
        },
        {
          type: "boolean",
          name: "allowAlwaysEdit",
          title: "Always Editable (allowAlwaysEdit)",
          labelTrue: "Yes",
          labelFalse: "No",
          isRequired: true,
          defaultValue: false,
        },
        {
          type: "boolean",
          name: "allowBpStartersViewAll",
          title: "BP Starters Can View All (allowBpStartersViewAll)",
          labelTrue: "Yes",
          labelFalse: "No",
          defaultValue: false,
          isRequired: true,
          startWithNewLine: false,
        },
        {
          type: "boolean",
          name: "allowElevatedViewAll",
          title: "Elevated Users Can View All (allowElevatedViewAll)",
          labelTrue: "Yes",
          labelFalse: "No",
          isRequired: true,
          defaultValue: false,
        },
        {
          type: "boolean",
          name: "startByDefault",
          title: "Start By Default (startByDefault)",
          labelTrue: "Yes",
          labelFalse: "No",
          isRequired: true,
          defaultValue: true,
        },

        {
          type: "text",
          name: "bpStartTriggerGv",
          visibleIf: "!{startByDefault}",
          title: "BP Start Global Variable",
          placeholder: "Enter trigger by information",
        },
        {
          type: "dropdown",
          name: "bpStartTriggerOperator",
          visibleIf: "!{startByDefault}",
          title: "BP Start Trigger Operator",
          placeholder: "Enter trigger operator",
          startWithNewLine: false,
          choicesByUrl: {
            url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/surveyjs/selectItems?type=operators`,
            path: "operators",
            valueName: "name",
            titleName: "label",
          },
        },
        {
          type: "text",
          name: "bpStartTriggerValue",
          visibleIf: "!{startByDefault}",
          title: "BP Start Trigger Value",
          placeholder: "Enter trigger value",
          startWithNewLine: false,
        },
        {
          type: "text",
          name: "startDate",
          title: "Start Date",
          inputType: "date",
          placeholder: "Enter start date",
        },
        {
          type: "text",
          inputType: "number",
          name: "noOfDaysLiveAfterBpStart",
          title: "Days Live After BP Start",
          startWithNewLine: false,
        },
        {
          type: "text",
          inputType: "number",
          name: "noOfDaysLiveAfterWfStart",
          title: "Days Live After WF Start",
          startWithNewLine: false,
        },
        {
          type: "boolean",
          name: "caCanUpdateDurationParams",
          title: "Allow CA to Update Duration",
          labelTrue: "Yes",
          labelFalse: "No",
          defaultValue: false,
        },
        {
          type: "matrixdynamic",
          name: "globalVariables",
          title: "Global Variables",
          columns: [
            {
              name: "globalVariables",
              title: "Name",
              cellType: "text",
              isRequired: true,
              placeholder: "Enter Global Variable...",
            },
          ],
          rowCount: 0,
          confirmDelete: true,
          confirmDeleteText:
            "Are you sure you want to delete this global variable?",
          addRowText: "Add a global variable",
          removeRowText: "Delete this global variables",
          hideColumnsIfEmpty: true,
          emptyRowsText:
            "No GV's entered yet.\nClick 'Add a global variable' to add a new one.\nClick the delete icon to remove an existing entry.",
        },
        {
          type: "comment",
          autoGrow: true,
          name: "notificationTriggers",
          title: "Notification Triggers",
          visible: false,
          placeholder: "JSON of notification triggers",
        },
        {
          type: "boolean",
          name: "saveAllowed",
          title: "Is Save Allowed?",
          labelTrue: "Yes",
          labelFalse: "No",
          defaultValue: false,
        },
      ],
    },
    {
      name: "contributor-functionality",
      title: "Contributors",
      elements: [
        {
          type: "boolean",
          name: "contributorFunctionality",
          title: "Enable Contributor Functionality",
          labelTrue: "Yes",
          labelFalse: "No",
          defaultValue: false,
        },
        {
          type: "comment",
          name: "contributorReason",
          visibleIf: "{contributorFunctionality}",
          title: "Reason for Contributor",
          isRequired: true,
          autoGrow: true,
          placeholder: "Enter description",
        },
        {
          type: "text",
          name: "minRequired",
          visibleIf: "{contributorFunctionality}",
          title: "# Minimum Required?",
          inputType: "number",
        },
        {
          type: "text",
          inputType: "number",
          name: "maxRequired",
          visibleIf: "{contributorFunctionality}",
          title: "# Maximum Required?",
          startWithNewLine: false,
        },
        {
          type: "comment",
          name: "altContributorTerm",
          title: "Action Contributor Term",
          visibleIf: "{contributorFunctionality}",
          placeholder: "Enter action contributor term",
        },
      ],
    },
    {
      name: "images-locations",
      title: "Images",
      elements: [
        {
          type: "text",
          name: "smallIconImageUrl",
          title: "Small Icon Image URL",
          placeholder: "Enter small icon image URL",
        },
        {
          type: "text",
          name: "largeIconImageUrl",
          title: "Large Icon Image URL",
          placeholder: "Enter large icon image URL",
        },
      ],
    },
  ],
};
