export const dashboardJson = {
    pages: [
        {
            name: "dashboard-info",
            title: "Dashboard Info",
            elements: [
                {
                    type: "text",
                    name: "name",
                    title: "Dashboard Name",
                    isRequired: true,
                    placeholder: "Enter the name of the dashboard",
                },
                {
                    type: "boolean",
                    name: "isActive",
                    title: "Is Active",
                    defaultValue: true,
                    isRequired: true,
                    labelTrue: "Yes",
                    labelFalse: "No",
                    startWithNewLine: false,
                },
                {
                    type: "boolean",
                    name: "teamManagerRequired",
                    title: "Team Manager Required",
                    defaultValue: false,
                    isRequired: false,
                    labelTrue: "Yes",
                    labelFalse: "No",
                },
                {
                    type: "boolean",
                    name: "deptManagerRequired",
                    title: "Department Manager Required",
                    defaultValue: false,
                    isRequired: false,
                    labelTrue: "Yes",
                    labelFalse: "No",
                    startWithNewLine: false,
                },
                {
                    type: "comment",
                    name: "description",
                    title: "Dashboard Description",
                    isRequired: true,
                    placeholder: "Enter a short description of the dashboard",
                },
                {
                    type: "dropdown",
                    name: "userRole",
                    title: "User Role",
                    isRequired: false,
                    choices: ["CU", "CL", "CS", "CA"],
                },
                {
                    type: "text",
                    name: "dashboardUrl",
                    title: "Dashboard URL",
                    isRequired: true,
                    inputType: "url",
                    placeholder: "Enter the URL for the dashboard",
                },
                {
                    type: "dropdown",
                    name: "availableAs",
                    title: "Available As",
                    isRequired: true,
                    choices: ["dashboard"], // Modify this based on actual options
                    placeholder: "Select how the dashboard is available",
                },
                {
                    type: "tagbox",
                    name: "userAccessGroupNames",
                    title: "User Access Group Names",
                    placeholder: "Enter user access group names",
                    choicesByUrl: {
                        url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/userGroupPlatform`,
                        path: "resource",
                        valueName: "name",
                        titleName: "name",
                    },
                },
                {
                    type: "text",
                    name: "smallIconImageUrl",
                    title: "Small Icon Image URL",
                    isRequired: false,
                    inputType: "url",
                    placeholder: "Enter the URL for the small icon image",
                },
                {
                    type: "text",
                    name: "largeIconImageUrl",
                    title: "Large Icon Image URL",
                    isRequired: false,
                    inputType: "url",
                    placeholder: "Enter the URL for the large icon image",
                    startWithNewLine: false,
                },
                {
                    type: "tagbox",
                    name: "customerRestrictionList",
                    title: "Customer Access",
                    titleLocation: "top",
                    placeholder: "Select Customers...",
                    choicesByUrl: {
                        url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/customer/allBy?isActive=true&parentId=null`,
                        path: "resource",
                        valueName: "id",
                        titleName: "name",
                    },
                },
            ],
        },
    ],
};
