export const emailSecureLinkJson = {
  pages: [
    {
      name: "email-secureLink-details",
      title: "Email Secure Link",
      elements: [
        {
          type: "boolean",
          name: "isActive",
          minWidth: "256px",
          title: "Active?",
          titleLocation: "top",
          description: "Is this email link active?",
          descriptionLocation: "underInput",
          defaultValue: false,
          isRequired: true,
          labelTrue: "Yes",
          labelFalse: "No",
          swapOrder: true,
        },
        {
          type: "boolean",
          name: "adminGenerated",
          minWidth: "256px",
          startWithNewLine: false,
          title: "Admin Generated?",
          titleLocation: "top",
          defaultValue: true,
          isRequired: true,
          labelTrue: "Yes",
          labelFalse: "No",
          swapOrder: true,
          readOnly: true,
        },
        {
          type: "text",
          name: "name",
          title: "Name",
          titleLocation: "top",
          isRequired: false,
          maxLength: 200,
          placeholder: "Enter name if required",
        },

        {
          type: "text",
          name: "expirationDate",
          title: "Expiration Date",
          defaultValueExpression: "today()",
          isRequired: true,
          inputType: "date",
        },
        {
          type: "dropdown",
          name: "actionType",
          title: "Action Type",
          titleLocation: "top",
          isRequired: true,
          startWithNewLine: false,
          placeholder: "Select action type",
          choices: [
            {
              value: "create",
              text: "Create",
            },
            {
              value: "contribute",
              text: "Contribute",
            },
            {
              value: "direct",
              text: "Direct",
            },
          ],
        },
        {
          type: "dropdown",
          name: "toolId",
          title: "Tool Config",
          isRequired: true,
          choicesByUrl: {
            url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/surveyjs/view?view=vwToolsConfigList`,
            valueName: "id",
            titleName: "name",
          },
        },
        {
          type: "dropdown",
          name: "workflowId",
          title: "Workflow",
          titleLocation: "top",
          enableIf: "{toolId} notempty",
          visibleIf: "{toolId} notempty",
          placeholder: "Select Workflow",
          choicesByUrl: {
            url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/surveyjs/view?view=vwToolToWorkflow&toolConfigId={toolId}`,
            valueName: "workflowId",
            titleName: "wfName",
          },
        },
        {
          type: "dropdown",
          name: "businessProcessId",
          title: "Business Process",
          titleLocation: "top",
          placeholder: "Select Business Process",
          enableIf: "{workflowId} notempty",
          visibleIf: "{workflowId} notempty",
          choicesByUrl: {
            url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/surveyjs/view?view=vwWorkflowToBusinessProcess&workflowId={workflowId}`,
            valueName: "businessProcessId",
            titleName: "bpName",
          },
        },
        {
          type: "dropdown",
          name: "toCustomerId",
          title: "Customer",
          choicesByUrl: {
            url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/customer/allBy`,
            path: "resource",
            valueName: "id",
            titleName: "name",
          },
        },
        {
          type: "dropdown",
          name: "toUserId",
          title: "User",
          enableIf: "{toCustomerId} notempty",
          visibleIf: "{toCustomerId} notempty",
          choicesByUrl: {
            url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/user/allBy?customerId={toCustomerId}`,
            path: "resource",
            valueName: "id",
            titleName: "email",
          },
        },
        {
          type: "text",
          name: "directPath",
          title: "Direct Path",
          isRequired: false,
        },
        {
          type: "boolean",
          name: "oneTimeLink",
          minWidth: "256px",
          title: "One Time Link?",
          titleLocation: "top",
          isRequired: false,
          labelTrue: "Yes",
          labelFalse: "No",
          swapOrder: true,
        },
        {
          type: "dropdown",
          name: "loginLink",
          title: "Login Link",
          titleLocation: "top",
          isRequired: false,
          choices: [
            {
              value: "no",
              text: "No",
            },
            {
              value: "user",
              text: "User",
            },
            {
              value: "anonymous",
              text: "Anonymous",
            },
          ],
        },
      ],
    },
  ],
};
