export const siteJson = {
  pages: [
    {
      name: "customer-address-site",
      title: "Site Details",
      elements: [
        {
          type: "boolean",
          name: "isActive",
          title: "Is this site active?",
          titleLocation: "top",
          defaultValue: true,
          isRequired: true,
          labelTrue: "Yes",
          labelFalse: "No",
          swapOrder: true,
        },
        {
          type: "text",
          name: "customerId",
          visible: false,
          defaultValueExpression: "{pgv_currentUser.customerId}",
          readOnly: true,
        },
        {
          type: "dropdown",
          name: "customerId",
          visibleIf:
            "{pgv_currentUser.role} = 'PA' or {wgv_siteType.siteTypeParam} = 'external'",
          title: "Customer",
          isRequired: true,
          choicesByUrl: {
            url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/customer/allBy`,
            path: "resource",
            valueName: "id",
            titleName: "name",
          },
        },
        {
          type: "text",
          name: "siteName",
          title: "Site Name",
          titleLocation: "top",
          isRequired: true,
          placeholder: "Enter site Name",
        },
        {
          type: "dropdown",
          name: "siteTypeId",
          startWithNewLine: false,
          title: "Site Type",
          titleLocation: "top",
          isRequired: true,
          renderAs1: "select",
          placeholder: "What type of site is this",
          allowClear: true,
          choicesByUrl: {
            url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/surveyjs/selectItems?type=site_type`,
            path: "site_type",
            valueName: "value",
            titleName: "label",
          },
        },
        {
          type: "text",
          name: "address1",
          titleLocation: "hidden",
          isRequired: true,
          placeholder: "No. / Name & Street",
        },
        {
          type: "text",
          name: "address2",
          startWithNewLine: false,
          titleLocation: "hidden",
          isRequired: false,
          placeholder: "Area",
        },
        {
          type: "text",
          name: "address3",
          titleLocation: "hidden",
          isRequired: true,
          placeholder: "Town / City",
        },
        {
          type: "text",
          name: "address4",
          startWithNewLine: false,
          titleLocation: "hidden",
          isRequired: true,
          placeholder: "Region",
        },
        {
          type: "text",
          name: "postcode",
          titleLocation: "hidden",
          isRequired: true,
          placeholder: "Postcode",
        },
        {
          type: "dropdown",
          name: "country",
          startWithNewLine: false,
          titleLocation: "hidden",
          isRequired: true,
          placeholder: "Country",
          defaultValue: "GB",
          choicesOrder: "asc",
          choicesByUrl: {
            url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/surveyjs/selectItems?type=country`,
            path: "country",
            valueName: "value",
            titleName: "label",
          },
        },
        {
          type: "expression",
          name: "latitude",
          title: "Latitude",
          setValueExpression: "fetchPostcodeData({postcode},'result.latitude')",
          titleLocation: "top",
          isRequired: false,
          readOnly: true,
          placeholder: "Latitude",
        },
        {
          type: "expression",
          name: "longitude",
          title: "Longitude",
          setValueExpression:
            "fetchPostcodeData({postcode},'result.longitude')",
          titleLocation: "top",
          isRequired: false,
          readOnly: true,
          placeholder: "Longitude",
          startWithNewLine: false,
        },
      ],
    },
    {
      name: "sitecontact-details-section",
      title: "Contact Details",
      elements: [
        {
          type: "dropdown",
          name: "primaryContactId",
          title: "Primary Contact (Site)",
          titleLocation: "top",
          enableIf: "{customerId} notempty",
          placeholder: "Select primary contact at this site / office",
          choicesByUrl: {
            url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/user/allBy?selectColumns=id,email,customerId&customerId={customerId}`,
            path: "resource",
            valueName: "id",
            titleName: "email",
          },
        },
        {
          type: "text",
          name: "siteTel",
          title: "Site Tel.",
          titleLocation: "top",
          inputType: "tel",
          maskType: "pattern",
          maskSettings: {
            pattern: "9999 9999999",
          },
          placeholder: "Enter site telephone",
        },
        {
          type: "text",
          name: "siteEmail",
          title: "Site Email",
          titleLocation: "top",
          isRequired: true,
          inputType: "email",
          placeholder: "Enter site email",
        },
      ],
    },
  ],
};
