export const tagsJson = {
  pages: [
    {
      name: "tag-creator-admin",
      title: "Tag Creator",
      elements: [
        {
          type: "boolean",
          name: "isActive",
          minWidth: "256px",
          title: "Active?",
          titleLocation: "top",
          description: "Is this Tag active?",
          descriptionLocation: "underInput",
          defaultValue: true,
          isRequired: true,
          labelTrue: "Yes",
          labelFalse: "No",
          swapOrder: true,
        },
        {
          type: "boolean",
          name: "isPublic",
          title: "Public Tag?",
          titleLocation: "top",
          description: "Is this Tag public and available for all customers?",
          descriptionLocation: "underInput",
          startWithNewLine: false,
          defaultValue: false,
          visibleIf: "{pgv_currentUser.role} = 'PA'",
          isRequired: true,
          labelTrue: "Yes",
          labelFalse: "No",
          swapOrder: true,
        },
        {
          type: "text",
          name: "customerId",
          title: "Customer",
          titleLocation: "top",
          defaultValueExpression: "{pgv_currentUser.customerId}",
          visible: false,
          readOnly: true,
        },
        {
          type: "dropdown",
          name: "customerId",
          title: "Customer",
          titleLocation: "top",
          placeholder: "Select customer",
          isRequired: true,
          description: "Customer this list is belongs to",
          descriptionLocation: "underInput",
          visibleIf: "{isPublic} = false and {pgv_currentUser.role} = 'PA'",
          choicesByUrl: {
            url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/customer/allBy?parentId=null`,
            path: "resource",
            valueName: "id",
            titleName: "name",
          },
        },
        {
          type: "text",
          name: "name",
          title: "Name",
          titleLocation: "top",
          isRequired: true,
          maxLength: 30,
          placeholder: "Enter tag name",
        },
        {
          type: "text",
          name: "colour",
          isRequired: true,
          defaultValue: "#000000",
          title: "Select a colour",
          inputType: "color",
          placeholder: "Pick colour",
        },
        {
          type: "text",
          name: "score",
          startWithNewLine: false,
          title: "Score Value",
          titleLocation: "top",
          defaultValue: 1,
          inputType: "number",
          min: 1,
          max: 10,
          placeholder: "Enter score value",
        },
        {
          type: "text",
          name: "weight",
          startWithNewLine: false,
          title: "Weighting Value",
          titleLocation: "top",
          defaultValue: 1,
          inputType: "number",
          min: 1,
          max: 10,
          placeholder: "Enter weight value",
        },
        {
          type: "text",
          name: "icon",
          title: "Icon Image Path",
          titleLocation: "top",
          isRequired: false,
          maxLength: 255,
          placeholder: "Enter an optional icon path",
        },
      ],
    },
  ],
};
