export const toolsJson = {
  pages: [
    {
      name: "toolConfig-creator-admin",
      title: "Tool Creator",
      elements: [
        {
          type: "boolean",
          name: "isActive",
          title: "Is Active?",
          labelTrue: "Yes",
          labelFalse: "No",
          defaultValue: true,
          isRequired: true,
          swapOrder: true,
        },
        {
          type: "text",
          name: "name",
          title: "Tool Name",
          titleLocation: "top",
          isRequired: true,
          maxLength: 100,
          placeholder: "Enter toolConfig name",
        },
        {
          type: "text",
          name: "displayName",
          title: "Display Name",
          titleLocation: "top",
          isRequired: true,
          placeholder: "Enter display name",
        },
        {
          type: "comment",
          name: "description",
          title: "Description",
          autoGrow: true,
          isRequired: true,
          placeholder: "Enter toolConfig description",
        },
        {
          type: "comment",
          name: "previewText",
          title: "Preview Text",
          autoGrow: true,
          isRequired: true,
          placeholder: "Enter preview text",
        },
        {
          type: "boolean",
          name: "showInSeeMoreList",
          title: "Show in see more list?",
          titleLocation: "top",
          defaultValue: false,
          labelTrue: "Yes",
          labelFalse: "No",
          swapOrder: true,
          isRequired: true,
        },
        {
          type: "tagbox",
          name: "userAccessGroupNames",
          title: "User Access Group Names",
          titleLocation: "top",
          placeholder: "Enter user access group names",
          choicesByUrl: {
            url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/userGroupPlatform`,
            path: "resource",
            valueName: "name",
            titleName: "name",
          },
        },
        {
          type: "dropdown",
          name: "categoryId",
          isRequired: true,
          title: "Tool Category",
          choicesByUrl: {
            url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/toolCategory/allBy`,
            path: "resource",
            valueName: "id",
            titleName: "name",
          },
        },
        {
          type: "text",
          name: "iconImageUrl",
          title: "Icon Image URL",
          titleLocation: "top",
          placeholder: "Enter the URL for the icon image",
        },
        {
          type: "text",
          name: "thumbnailImageUrl",
          title: "Thumbnail Image URL",
          titleLocation: "top",
          placeholder: "Enter the URL for the thumbnail image",
        },
        {
          type: "text",
          name: "previewImageUrl",
          title: "Preview Image URL",
          titleLocation: "top",
          placeholder: "Enter the URL for the preview image",
        },
        {
          type: "text",
          name: "appUrl",
          title: "App URL",
          titleLocation: "top",
          placeholder: "Enter the app URL",
        },
        {
          type: "text",
          name: "logoImageUrl",
          title: "Logo Image URL",
          placeholder: "Enter the URL for the logo image",
        },
      ],
    },
    {
      name: "toolConfig-associated-workflows",
      title: "Associated Workflows",
      elements: [
        {
          type: "paneldynamic",
          name: "toolWorkflow",
          width: "100%",
          minWidth: "256px",
          title: "Worflows",
          titleLocation: "hidden",
          panelCount: 1,
          minPanelCount: 1,
          confirmDeleteText: "Do you want to delete workflow?",
          panelAddText: "Add Workflow",
          panelRemoveText: "Delete Workflow",
          showRangeInProgress: false,
          templateElements: [
            {
              type: "dropdown",
              name: "workflowId",
              title: "Associated Workflow #{panelIndex}",
              titleLocation: "top",
              placeholder: "Select Workflow",
              isRequired: true,
              choicesByUrl: {
                url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/workflow/allBy?selectColumns=id,name&isActive=true`, // The API endpoint to fetch choices from
                path: "resource",
                valueName: "id",
                titleName: "name",
              },
            },
            {
              type: "boolean",
              name: "caCanUpdateScheduleFrequency",
              title: "CAs update schedules?",
              titleLocation: "top",
              width: "33%",
              description: "Can CAs update schedules?",
              descriptionLocation: "underInput",
              defaultValue: false,
              isRequired: true,
              labelTrue: "Yes",
              labelFalse: "No",
              swapOrder: true,
            },
            {
              type: "boolean",
              name: "isReadOnly",
              title: "Read Only?",
              titleLocation: "top",
              width: "33%",
              startWithNewLine: false,
              description: "Is this tool read only",
              descriptionLocation: "underInput",
              defaultValue: false,
              isRequired: true,
              labelTrue: "Yes",
              labelFalse: "No",
              swapOrder: true,
            },
            {
              type: "boolean",
              name: "isActive",
              width: "33%",
              startWithNewLine: false,
              title: "Active?",
              titleLocation: "top",
              description: "Is this tool active?",
              descriptionLocation: "underInput",
              defaultValue: false,
              isRequired: true,
              labelTrue: "Yes",
              labelFalse: "No",
              swapOrder: true,
            },
          ],
        },
      ],
    },
  ],
};
