export const toolsJson = {
    pages: [
        {
            name: "toolConfig-creator-admin",
            title: "Tool Creator",
            elements: [
                {
                    type: "boolean",
                    name: "isActive",
                    title: "Is Active?",
                    labelTrue: "Yes",
                    labelFalse: "No",
                    defaultValue: true,
                    swapOrder: true,
                },
                {
                    type: "text",
                    name: "name",
                    title: "Tool Name",
                    titleLocation: "top",
                    isRequired: true,
                    maxLength: 100,
                    placeholder: "Enter toolConfig name",
                },
                {
                    type: "text",
                    name: "displayName",
                    title: "Display Name",
                    titleLocation: "top",
                    isRequired: true,
                    placeholder: "Enter display name",
                },
                {
                    type: "comment",
                    name: "description",
                    title: "Description",
                    autoGrow: true,
                    placeholder: "Enter toolConfig description",
                },
                {
                    type: "comment",
                    name: "previewText",
                    title: "Preview Text",
                    autoGrow: true,
                    placeholder: "Enter preview text",
                },
                {
                    type: "text",
                    name: "iconImageUrl",
                    title: "Icon Image URL",
                    titleLocation: "top",
                    placeholder: "Enter the URL for the icon image",
                },
                {
                    type: "text",
                    name: "thumbnailImageUrl",
                    title: "Thumbnail Image URL",
                    titleLocation: "top",
                    placeholder: "Enter the URL for the thumbnail image",
                },
                {
                    type: "text",
                    name: "previewImageUrl",
                    title: "Preview Image URL",
                    titleLocation: "top",
                    placeholder: "Enter the URL for the preview image",
                },
                {
                    type: "text",
                    name: "appUrl",
                    title: "App URL",
                    titleLocation: "top",
                    placeholder: "Enter the app URL",
                },
                {
                    type: "text",
                    name: "logoImageUrl",
                    title: "Logo Image URL",
                    placeholder: "Enter the URL for the logo image",
                },
            ],
        },
    ],
};
