export const userGroupJson = {
  pages: [
    {
      name: "user-group-details",
      title: "User Group",
      elements: [
        {
          type: "boolean",
          name: "isActive",
          minWidth: "256px",
          title: "Is user group active?",
          titleLocation: "top",
          defaultValue: true,
          isRequired: true,
          labelTrue: "Yes",
          labelFalse: "No",
          swapOrder: true,
          readOnly: false,
        },
        {
          type: "boolean",
          name: "isPlatform",
          visibleIf: "{pgv_currentUser.role} = 'PA'",
          minWidth: "256px",
          title: "Is this a platform level group?",
          titleLocation: "top",
          defaultValueExpression:
            "iif({pgv_currentUser.role} = 'PA', true, false)",
          isRequired: true,
          labelTrue: "Yes",
          labelFalse: "No",
          swapOrder: true,
          readOnly: true,
          startWithNewLine: false,
        },
        {
          type: "text",
          name: "customerId",
          title: "Customer",
          readOnly: true,
          visible: false,
          // visibleIf: "{pgv_currentUser.role} != 'PA'",
          defaultValueExpression: "{pgv_currentUser.customerId}",
        },
        {
          type: "text",
          name: "name",
          title: "User Group Name",
          titleLocation: "top",
          isRequired: true,
          enableIf: "{pgv_currentUser.role} = 'PA'",
          maxLength: 200,
          placeholder: "Enter name",
          readOnly: false,
        },
        {
          type: "comment",
          name: "description",
          title: "Description",
          titleLocation: "top",
          isRequired: true,
          maxLength: 300,
          placeholder: "Enter description",
          readOnly: false,
        },
      ],
    },
  ],
};
