export const workflowJson = {
    pages: [
        {
            name: "workflow-creator-admin",
            title: "Workflow Creator",
            elements: [
                {
                    type: "boolean",
                    name: "isActive",
                    title: "Is Active?",
                    labelTrue: "Yes",
                    labelFalse: "No",
                    defaultValue: true,
                    swapOrder: true,
                },
                {
                    type: "boolean",
                    name: "anonymousSubmission",
                    title: "Anonymous Workflow?",
                    labelTrue: "Yes",
                    labelFalse: "No",
                    defaultValue: true,
                    swapOrder: true,
                },
                {
                    type: "text",
                    name: "name",
                    title: "Workflow Name",
                    titleLocation: "top",
                    isRequired: true,
                    maxLength: 100,
                    placeholder: "Enter workflow name",
                },
                {
                    type: "comment",
                    name: "description",
                    title: "Description",
                    autoGrow: true,
                    placeholder: "Enter workflow description",
                },
                {
                    type: "tagbox",
                    name: "userAccessGroupNames",
                    title: "User Access Group Names",
                    titleLocation: "top",
                    placeholder: "Enter user access group names",
                    choicesByUrl: {
                        url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/userGroupPlatform`,
                        path: "resource",
                        valueName: "name",
                        titleName: "name",
                    },
                },
                {
                    type: "text",
                    inputType: "date",
                    name: "startDate",
                    title: "Start Date",
                    titleLocation: "top",
                    placeholder: "Workflow Start Date",
                },

                {
                    type: "boolean",
                    name: "enableStartNewInUi",
                    title: "Enable Start New in UI",
                    isRequired: true,
                    labelTrue: "Yes",
                    labelFalse: "No",
                    defaultValue: true,
                },
                {
                    type: "boolean",
                    name: "caCanUpdateStartDate",
                    title: "Can Update Start Date",
                    labelTrue: "Yes",
                    labelFalse: "No",
                    defaultValue: false,
                },
                {
                    type: "text",
                    name: "noOfDaysLiveAfterStart",
                    startWithNewLine: false,
                    title: "Number of days live after start",
                    titleLocation: "top",
                    inputType: "number",
                    placeholder: "Number of days live after start",
                },
                {
                    type: "boolean",
                    name: "caCanUpdateDuration",
                    title: "Can Update Duration",
                    labelTrue: "Yes",
                    labelFalse: "No",
                    defaultValue: false,
                },
                {
                    type: "text",
                    name: "jsAdditionalFileUrl",
                    title: "JS Additional File URL",
                    placeholder: "Enter URL for additional JS file",
                },
                {
                    type: "text",
                    name: "cssThemeFileUrl",
                    title: "CSS Theme File URL",
                    placeholder: "Enter URL for CSS theme",
                },
                {
                    type: "text",
                    name: "sjsThemeFileUrl",
                    title: "SJS Theme File URL",
                    placeholder: "Enter URL for SJS theme",
                },
            ],
        },
        {
            name: "workflow-associated-business-processes",
            title: "Associated BPs",
            elements: [
                {
                    type: "matrixdynamic",
                    name: "workflowBusinessProcess",
                    width: "100%",
                    title: "Associated Business Processes",
                    titleLocation: "hidden",
                    rowCount: 0,
                    allowRemoveRows: true,
                    detailPanelMode: "underRowSingle",
                    allowRowsDragAndDrop: true,
                    addRowText: "Add Business Process",
                    panelRemoveText: "Delete Business Process",
                    columns: [
                        {
                            cellType: "dropdown",
                            name: "businessProcessId",
                            title: "Associated BPs #{panelIndex}",
                            titleLocation: "top",
                            isRequired: true,
                            placeholder: "Select Business Process",
                            choicesByUrl: {
                                url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/businessProcess/allBy?selectColumns=id,name&isActive=true`,
                                path: "resource",
                                valueName: "id",
                                titleName: "name",
                            },
                        },
                        {
                            cellType: "expression",
                            name: "businessProcessOrder",
                            startWithNewLine: false,
                            title: "Order",
                            titleLocation: "top",
                            inputType: "number",
                            expression: "{rowIndex}",
                            placeholder: "BP Order",
                        },
                    ],
                },
            ],
        },
    ],
};
